### ISSUE TITLE
Unlock code mem address

### ISSUE THREAD

**Issue by orllewin** [cranksters/playdate-reverse-engineering#17]
The address for the serial unlock code seems to have changed, `(const char*)0x1FF0F040` now throws an error. 

If anyone could help me find the unlock code I'd be forever grateful, I really need full serial access for a hardware project I'm half way through.

**Comment by scratchminer** [comment]
If the error is `Error accessing buffer at 0x1FF0F040`, that's because the app using it isn't running wth system privileges.

**Comment by laplab** [comment]
@scratchminer What does one need to run the app with system privileges?

**Comment by castholm** [comment]
I realize that this is over a year later, but 0ad50d25eb6fbbde5ab258629578ab9c3a99e6f4 from #26 added some more information about the process for obtaining the unlock code. Please check and see if those new details help you find your unlock code, and if not, feel free to reopen the issue.
